# Generated by Django 5.1.2 on 2024-10-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='image',
            field=models.ImageField(blank=True, default='wishlist_images/default_image.jpg', null=True, upload_to='wishlist_images/', verbose_name='изображение'),
        ),
    ]
