# Generated by Django 5.1.2 on 2024-10-31 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_alter_wishlist_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlist',
            options={'ordering': ('updated_at',), 'verbose_name': 'Желание', 'verbose_name_plural': 'Желания'},
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='url',
            field=models.URLField(verbose_name='ссылка на желание'),
        ),
    ]
