# Generated by Django 5.1.2 on 2024-11-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0004_wishlist_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='views_count',
            field=models.BooleanField(default=0, verbose_name='проосмотры'),
        ),
    ]
